### ISSUE TITLE
Command to stop recurring hourly snapshots

### ISSUE THREAD

**Issue by BRENTH561** [apprell/proxmox-autosnap#11]
I did proxmox-autosnap.py --snap --vmid all --label hourly

I would now like to stop all hourly autosnap from occurring. 

What is the command I need to run to do so?

**Comment by apprell** [comment]
If you run script it once from the terminal, it will take snapshots only once, it is not a service that does its work automatically every hour.

If you have not added a task to CRON as described in README, you do not need to do anything else, if you have added it, you need to delete the task in CRON.

**Comment by BRENTH561** [comment]
If i go to nano /etc/cron.d/autosnap      

i see the following:
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Task for snapshot every hour from 1 through 23.
5 1-23 * * * root /usr/local/sbin/proxmox-autosnap.py --autosnap --vmid all --label hourly --keep 23 --mute

# Task for snapshot every day-of-month from 2 through 31.
5 0 2-31 * * root /usr/local/sbin/proxmox-autosnap.py --autosnap --vmid all --label daily --keep 30 --mute

# Task for snapshot at 00:05 on day-of-month 1.
5 0 1 * * root /usr/local/sbin/proxmox-autosnap.py --autosnap --vmid all --label monthly --keep 3 --mute

So do i need to delete all of these entries and then write out?



Following your video I do not recall making any changes in nano other than adding the ssl keys from true nas. 

I believe all i did was:
git clone https://github.com/apprell/proxmox-autosnap.git
ln -s /root/proxmox-autosnap/proxmox-autosnap.py /usr/local/sbin/proxmox-autosnap.py
ln -s /root/proxmox-autosnap/autosnap /etc/cron.d/autosnap
chmod +x /root/proxmox-autosnap/proxmox-autosnap.py

then 
proxmox-autosnap.py --snap --vmid all --label hourly

**Comment by apprell** [comment]
If you want to disable only taking snapshots once an hour but keep the others, you just need to delete one line from file `/etc/cron.d/autosnap`:

`5 1-23 * * * * root /usr/local/sbin/proxmox-autosnap.py --autosnap --vmid all --label hourly --keep 23 --mute`

If you want to fully disable automatic snapshot creation, you just need to remove the symlink:

`rm -f /etc/cron.d/autosnap`
