### ISSUE TITLE
How to add sending an email when autosnap has finished

### ISSUE THREAD

**Issue by greavette** [apprell/proxmox-autosnap#13]
Hello @apprell ,

I really appreciate you providing this script for all to use!  I think this is critical within Proxmox.

I'd like to add the function to send me an email when the auto_snap has successfully completed...or perhaps even better if auto_snap failed to complete for some reason.  How would I do this? Do I add it to my cron job?  Are there parms I need to use to verify the success of the auto_snap completing?  

Also, is there a setting within auto_snap to include RAM when the snapshot is taken?

Thanks in advance for any advice you can provide me.

**Comment by apprell** [comment]
Hello!

Since the script is run from `CRON`, if there is an error, `CRON` will send a message in case of an error.
To include `RAM` in the snapshot, there is an `includevmstate` option that you can use.

**Comment by greavette** [comment]
Thanks very much for this detail...much appreciative of your help!
