### ISSUE TITLE
How to make the snapshot run in minutes and not just hourly

### ISSUE THREAD

**Issue by greavette** [apprell/proxmox-autosnap#14]
Hello @apprell ,

I'm curious if I can modify this to allow for a snapshot in minutes instead of hourly being the shortest time frame to take a snapshot.  I was hoping to take a snapshot on one particular VM every 5 minutes or 10 minutes.  is this is possible what would I need to change please in order to achieve this?

Thank you in advance for any advice you can provide me.

**Comment by apprell** [comment]
Hello!

This can be done in the following way:

`*/15 * * * * root /usr/local/sbin/proxmox-autosnap.py --autosnap --vmid all --label hourly --keep 100 --mute`

> `--keep 100` needs to be changed to as many as you want.

But here it looks ugly `--label hourly`, I will add a new label `minute`

**Comment by apprell** [comment]
Added a new label `minute`:

`*/15 * * * * root /usr/local/sbin/proxmox-autosnap.py --autosnap --vmid all --label minute --keep 100 --mute`
