### ISSUE TITLE
Add ability to select or exclude VMs und CTs via label

### ISSUE THREAD

**Issue by zrav** [apprell/proxmox-autosnap#17]
Currently we can only select or exclude VMs and CTs from snapshotting via IDs. It would be great if we could do this via labels too. 
For instance, I could want to snapshot all VMs and CTs except those labeled "nosnap". 
So I could image an argument called --exclude-label. Or a complementary --include-label, which could be used instead of or in addition to --vmid.

**Comment by apprell** [comment]
Added tag-based filtering, here are some examples:

```bash
# Create a snapshot filtered by tags and exclude specific tags
# Tags are supported only in Proxmox version 7.3 and above
proxmox-autosnap.py --sudo --snap --tags snap --label hourly
proxmox-autosnap.py --sudo --snap --vmid all --label hourly --exclude-tags nosnap
```
